fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  service:
    mailer: fos_user.mailer.twig_swift
  from_email:
    address: 'info@ravemap.tk'
    sender_name: 'RAV3MAP'
  registration:
    confirmation:
      enabled: true
      template:   'Mail/confirmation.txt.twig'
